In [7]:
import numpy as np
def S(m,n):
    msn = m+n
    den = (msn+1)*(msn+3)*(msn+5)
    num = (1-(m+n)%2)*16
    return num/den

In [10]:
def H(m,n):
    msn = m+n 
    den = (msn+3)*(msn+1)*(msn-1)
    num = 1-m-n-2*m*n
    y = 0.0
    if np.abs(den) > 0.0:
        y = -num*8*(1-(m+n)%2)/den
    return y

In [11]:
import numpy as np
N_basis = 5
S_matrix = np.zeros((N_basis,N_basis))
H_matrix = np.zeros((N_basis,N_basis))
for i in range(N_basis):
    for j in range(N_basis):
        S_matrix[i,j] = S(i,j)
        H_matrix[i,j] = H(i,j)

* build V, U, s^(-1/2) matrix

In [13]:
from scipy import linalg
dig_s, U = np.linalg.eigh(S_matrix)

* calculate s^(-1/2)

In [15]:
half_s = np.zeros((N_basis,N_basis))
for i in range(N_basis):
    half_s[i,i] = 1.0E0/np.sqrt(np.abs(dig_s[i]))

* calculation V = US^(-1/2)

In [16]:
V = np.dot(U, half_s)

In [18]:
with np.printoptions(precision=6, suppress=True):
    print(np.dot(np.transpose(U),U))

[[ 1. -0.  0. -0.  0.]
 [-0.  1. -0.  0.  0.]
 [ 0. -0.  1. -0. -0.]
 [-0.  0. -0.  1.  0.]
 [ 0.  0. -0.  0.  1.]]


* calculation V^prime, C^prime

In [19]:
V_dagger = np.transpose(V)
tmp = np.dot(H_matrix,V)
H_prime = np.dot(V_dagger,tmp)

In [20]:
EE, C_prime = np.linalg.eigh(H_prime)
for i in range(N_basis):
    print('{:12.5f}'.format(EE[i]))

     2.46740
     9.87539
    22.29341
    50.12461
    87.73919


In [24]:
C = np.dot(V, C_prime)
C1 = np.dot(np.linalg.inv(V_dagger),np.dot(C_prime,np.linalg.inv(V)))
print (C, C1)

[[ 9.99989758e-01  2.64123063e-18  9.62512213e-01  8.82832840e-16
  -6.17024820e-01]
 [ 6.83584901e-16  3.07099182e+00 -1.31697105e-15 -3.89594459e+00
  -8.88721229e-15]
 [-2.33425559e-01 -6.35016128e-16 -8.98766320e+00 -1.65182241e-14
   1.30218207e+01]
 [-1.34619147e-15 -1.58762744e+00  2.21423343e-15  1.26452091e+01
   2.90034661e-14]
 [ 1.89585933e-02  6.01665581e-16  5.99363128e+00  3.28285364e-14
  -2.62659243e+01]] [[ 1.03737513e-02 -7.97904700e-17 -2.16169714e-02 -5.50141944e-17
   2.58962886e-02]
 [-6.54608239e-17 -2.83522544e-02 -2.09463485e-17  2.06441183e-02
   6.20966587e-18]
 [ 4.54187050e-02 -3.20044496e-17 -2.46643479e-02 -2.08075970e-17
  -1.02199112e-02]
 [-1.28285410e-16 -3.95456212e-02 -1.91978992e-17 -4.29579613e-03
  -2.34426047e-18]
 [ 6.15785379e-02 -4.79809701e-17 -5.92221528e-03 -2.02540792e-17
  -3.70119876e-03]]


* construct wavefunctions

In [ ]:
interval = 0.01
x = np.arange(-1,1+interval,interval)
def basis_f(x,n):
    y = x**n*(x-1)*(x+1)
    return y
y_tot = np.zeros((len(x),N_basis))
for j in range(N_basis):
    for i in range(N_basis):
        y_tot[:,j]+=basis_f(x,i)*C(i,j)